export { api, uploadApi, libraryApi, libraryUploadApi } from './client';

export { documentApi } from './documents';
export { folderApi } from './folders';
export { highlightApi } from './highlights';
export { optimizeApi } from './optimize';
export { countryApi, categoryApi, timePeriodApi, bookApi } from './library';
export { worldTimelineApi } from './timeline';
export { documentSourceApi, quarkApi } from './external';
export { duplicateApi } from './duplicate';
export { pdfOcrApi } from './ocr';
export { backupApi } from './backup';
export { dashboardApi } from './dashboard';
export { quickNoteApi } from './quickNotes';
export type { QuickNote, QuickNoteCreateRequest, QuickNoteAIResult } from './quickNotes';
export { chapterNoteApi } from './chapterNotes';
export type { ChapterNote, ChapterNoteCreateRequest, ChapterNoteGenerateRequest } from './chapterNotes';
export { taskApi } from './tasks';
export type { Task, TaskCreate } from './tasks';
export { activityApi } from './activity';
export type { Activity } from './activity';
